server:
  port: 8585
  rateLimit:
    retryAfter: 15 # value in minutes
    maximumTry: 10 # maximum number of continuous request to allow
    message: {'error': 'Too many request comming from this IP, please try again after an hour'}   

application:
  name: APIGateway

cloud:
  gateway:
    routes:
      - service: jobs
        predicates: jobs
      - service: institute
        predicates: institute
      - service: assessment
        predicates: assessment
    hostname:
      jobs: http://localhost:8080
      institute: http://localhost:7070
      assessment: http://localhost:9090

gateway:
  url:
    publicPath:
      - /auth/login
      - /expert/public/**
      - /jobs/api/v1/public/**
      - /restaurant/api/v1/restaurant
      - /institute/public/**
    authenticatedPath:
      - /auth/refresh/token
      - /auth/claims
      - /auth/password
      - /auth/logout
      - /auth/identity/session
      - /auth/identity/session/logout/all
      - /auth/identity/session/logout/*
      - /search/location/**
    privatePath:
      - /admin/**
      - /identity/private/**
      - /restaurant/private/**
      - /jobs/private/**
    logoutPath: /auth/logout
