server:
  port: 8585

application:
  name: APIGateway

cloud:
  gateway:
    routes:
      - service: restaurant
        predicates: restaurant
      - service: booking
        predicates: reservation
    hostname:
      restaurant: http://localhost:6060
      reservation: http://localhost:7070

gateway:
  url:
    publicPath:
      - /auth/login
      - /expert/public/**
      - /jobs/api/v1/public/**
      - /restaurant/api/v1/restaurant
    authenticatedPath:
      - /auth/refresh/token
      - /auth/claims
      - /auth/password
      - /auth/logout
      - /auth/identity/session
      - /auth/identity/session/logout/all
      - /auth/identity/session/logout/*
      - /search/location/**
    privatePath:
      - /admin/**
      - /identity/private/**
      - /restaurant/private/**
    logoutPath: /auth/logout
